server:
  port: 9527

spring:
  application:
    name: wolfcloud-zuul-gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true     #访问路径可以显示IP地址

zuul:
  prefix: /wolf
  #多个
  #ignored-services: "*"
  ignored-services: wolfcloud-user
  routes:
    myuser.service-id: wolfcloud-user
    myuser.path: /userinfo/**

info:
  app.name: wolf-cloud
  company.name: www.wolf.mission.com
  #TODO 一直无法正常显示
  build.artifactId: $project.artifactId$
  build.version: $project.version$
