server:
  port: 3344
spring:
  application:
    name: wolfcloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:xiaoxiaowAlways/wolfcloud-config.git
#          uri: https://github.com/xiaoxiaowAlways/wolfcloud-config.git

